### PR TITLE
build: Move semantic-release to CI

### PR DESCRIPTION
**Pull request by okonet**
Moves semantic-release to CI

### CODE REVIEW

**Comment by rkmarks** [comment]
@okonet looks like the CI failed to publish as it looks like 1.1.1 already exists

**Comment by okonet** [comment]
How come? Can you publish a new fix version?

**Comment by rkmarks** [comment]
I believe it was due to it not being updated w/ a tag. I have released the new tag and we may need to re-run the CI.

**Comment by rkmarks** [comment]
That didn't seem to work. We may have to delete the tag/release and let CI re-run from what I have been reading into. @okonet did you want me to handle this?

**Comment by okonet** [comment]
Yes, please go ahead.

**Pull request merged**
