### PR TITLE
Add .babelrc to .npmignore

### PR DESCRIPTION
**Pull request by jskorepa**
Same as https://github.com/react-dropzone/react-dropzone/pull/558

### CODE REVIEW

**Comment by okonet** [comment]
You might want to skip code from `node_modules` in Jest config (this is default BTW) instead of trying to fix all npm modules :)

**Comment by ajsharp** [comment]
After reading @jskorepa's issues on react-dropzone this sounds like it would fix the issue I'm having as well. Where do you stand on this @okonet? I'm not familiar with what's considered best practice in the community for publishing build configuration in the distributed package.

I agree this is probably the result of an overly optimistic assumption in parcel, and should maybe be changed there. Still, unless there's a good reason to ship the .babelrc file in the npm package, would you consider leaving it out?

**Comment by okonet** [comment]
I never used parcel before but it looks like something they should fix. I’m okay with merging this, though.

**Comment by okonet** [comment]
Please sync the branch and I’ll merge it

**Comment by jskorepa** [comment]
Rebased to current master. For anyone looking for solution which does not require patching lot of npm packages I ended up setting following script as "prepare" in package.json

```
const fs = require('fs')
const path = require('path')

for (const dep of fs.readdirSync('node_modules')) {
  const dir = path.join('node_modules', dep)
  const file = name => path.join(dir, name)
  // remove .babelrc
  try {
    const from = file('.babelrc')
    const to = file('.babelrc.bckp')
    fs.renameSync(from, to)
    console.log('Renamed', from, 'to', to)
  } catch (e) {
    // ignore error
  }
  // patch package.json to remove babel spec
  try {
    const pkg = JSON.parse(fs.readFileSync(file('package.json')))
    if (pkg.babel) {
      delete pkg.babel
      fs.renameSync(file('package.json'), file('package.json.bckp'))
      fs.writeFileSync(file('package.json'), JSON.stringify(pkg, 0, 2), 'utf-8')
    }
  } catch (e) {
    // ignore error
  }
}
```

**Comment by okonet** [comment]
Sorry for bike shedding, but why are you using parcell? Wasn't it zero-congif in the first place? So now you need to patch the whole internet to get a tool working? 🤔

**Comment by sapegin** [comment]
This is actually a very good thing to do but for another reason: you shouldn't publish unnecessary files (any tooling configs for example) to npm.

And webpack has the same issue, though it's easy to fix.

**Comment by okonet** [comment]
@sapegin I'm not sure about this in case you want to build from source (which is the case with webpack, afaik).

**Comment by ajsharp** [comment]
For anyone interested, the main discussion thread for this issue in parcel is here: https://github.com/parcel-bundler/parcel/issues/13.

I agree that parcel should not be doing this. Thanks @okonet for accommodating this change regardless!

**Pull request merged**
